# Generated by Django 5.1.1 on 2025-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='Согласие'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default=7777777, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
